server:
  port: 8084
  servlet:
    context-path: /au

spring:
  application:
    name: auth-service

  profiles:
    active: local

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 769888330185-go7cocbakom2gands6vm3rkqpicmj0ff.apps.googleusercontent.com
            client-secret: M0bEXZSW0_FH2U3dEakLBNog
            redirect-uri: http://localhost:8080/au/oauth2/callback/google

logging:
  level:
    org:
      springframework:
        web: DEBUG
        web.filter.CommonsRequestLoggingFilter: DEBUG
    com:
      demo: DEBUG

app:
  login-url: http://localhost:8080/au/custom-login
  home-url: http://localhost:8080/home
---

spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    url: jdbc:postgresql://localhost:5432/microservices-project-db
    username: postgres
    password: password



  zipkin:
    enabled: false

#  zipkin:
#    base-url: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

---

spring:
  config:
    activate:
      on-profile: "docker"

  datasource:
    url: jdbc:postgresql://postgres:5432/microservices-project-db
    username: postgres
    password: password

  zipkin:
    base-url: http://zipkin:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8083/eureka