server:
  port: 8081
  servlet:
    context-path: /cs

spring:
  application:
    name: comment-service

  profiles:
    active: local

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

---

spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    url: jdbc:postgresql://localhost:5432/microservices-project-db
    username: postgres
    password: password

  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

---

spring:
  config:
    activate:
      on-profile: "docker"

  datasource:
    url: jdbc:postgresql://postgres:5432/microservices-project-db
    username: postgres
    password: password

  zipkin:
    base-url: http://zipkin:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8083/eureka