server:
  port: 8081
  servlet:
    context-path: /cs

spring:
  application:
    name: comment-service
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/microservices-project-db
    username: postgres
    password: password
