server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: commentServiceRoute
          uri: lb://comment-service
          predicates:
            - Path= /cs/**
        - id: postServiceRoute
          uri: lb://post-service
          predicates:
            - Path= /ps/**
