server:
  port: 8080

spring:
  profiles:
    active: local

  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: commentServiceRoute
          uri: lb://comment-service
          predicates:
            - Path= /cs/**
        - id: postServiceRoute
          uri: lb://post-service
          predicates:
            - Path= /ps/**

---

spring:
  config:
    activate:
      on-profile: "local"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

---

spring:
  config:
    activate:
      on-profile: "docker"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8083/eureka