server:
  port: 8080

spring:
  profiles:
    active: local

  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: commentServiceRoute
          uri: lb://comment-service
          predicates:
            - Path= /cs/**
          filters:
            - AuthenticationCustomFilter
        - id: postServiceRoute
          uri: lb://post-service
          predicates:
            - Path= /ps/**
          filters:
            - AuthenticationCustomFilter
        - id: authServiceRouteAuthenticated
          uri: lb://auth-service
          predicates:
            - Path= /au/home/**
          filters:
            - name: AuthenticationCustomFilter
        - id: authServiceRouteWithoutFilter
          uri: lb://auth-service
          predicates:
            - Path= /au/**

---

spring:
  config:
    activate:
      on-profile: "local"

  zipkin:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka


---

spring:
  config:
    activate:
      on-profile: "docker"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8083/eureka