server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: commentServiceRoute
          uri: http://localhost:8081/
          predicates:
            - Path= /cs/**
        - id: postServiceRoute
          uri: http://localhost:8082/
          predicates:
            - Path= /ps/**
