server:
  port: 8083

spring:
  profiles:
    active: local

  application:
    name: discovery

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

---

spring:
  config:
    activate:
      on-profile: "local"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

---

spring:
  config:
    activate:
      on-profile: "docker"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8083/eureka