spring:
  application:
    name: discovery

server:
  port: 8083
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8083/eureka